sudo: false
language: ruby
rvm:
  - 2.5.3
before_install: gem install bundler -v 2.1.4
script:
  - make lint
  - make test
deploy:
  provider: rubygems
  api_key: $RUBYGEMS_APIKEY
  gem: appbooster_rubocop_config
