require:
  - ./lib/rubocop/appbooster_rubocop_config

AllCops:
  Include:
    - "Rakefile"
    - "config.ru"
    - "lib/**/*.rake"
  Exclude:
    - "bundle/**/*"
    - "vendor/**/*"
    - "db/**/*"
    - "script/**"
    - "node_modules/**/*"
    - "bin/**"
    - "*Gemfile*"
    - "*.gemspec"

Layout/SpaceInLambdaLiteral:
  EnforcedStyle: require_space

Layout/IndentHash:
  EnforcedStyle: consistent

# Commonly used screens these days easily fit more than 80 characters.
Metrics/LineLength:
  Max: 120

Metrics/AbcSize:
  Enabled: false

Metrics/ParameterLists:
  CountKeywordArgs: false

Naming/FileName:
  Exclude:
    - "Capfile"
    - "Vagrantfile"

Rails:
  Enabled: true

Rails/SkipsModelValidations:
  Enabled: true

VariableName:
  EnforcedStyle: snake_case

# Single quotes being faster is hardly measurable and only affects parse time.
# Enforcing double quotes reduces the times where you need to change them
# when introducing an interpolation. Use single quotes only if their semantics
# are needed.
Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/SafeNavigation:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Lint/UnlessMultipleConditions:
  Description: 'Do not use `unless` with multiple conditions.'
  Enabled: true
